# Generated by Django 4.2.20 on 2025-03-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asesor',
        ),
    ]
