# Generated by Django 4.2.20 on 2025-03-25 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('nomina', models.CharField(max_length=200)),
                ('tipoAsociado', models.CharField(max_length=200)),
                ('fechaultimaAfiliacion', models.CharField(max_length=200)),
                ('antiguedad', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('movil', models.CharField(max_length=200)),
                ('cartera', models.CharField(max_length=200)),
                ('aportes', models.CharField(max_length=200)),
                ('numeroAhorro', models.CharField(max_length=200)),
                ('cantidadAhorro', models.CharField(max_length=200)),
                ('numeroCooviaho', models.CharField(max_length=200)),
                ('cantidadCooviaho', models.CharField(max_length=200)),
                ('numeroCdat', models.CharField(max_length=200)),
                ('cantidadCdat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResgistrosAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('asesor', models.CharField(max_length=200)),
                ('observacion', models.TextField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.asociado')),
            ],
        ),
    ]
