# Generated by Django 4.2.7 on 2025-03-21 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('obsequio', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('causa', models.CharField(max_length=200)),
                ('preaprobado', models.CharField(max_length=200)),
                ('cuota', models.CharField(max_length=200)),
                ('plazo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EntregaObsequio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=200)),
                ('sucursal', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('obsequio', models.CharField(max_length=200)),
                ('asesor', models.CharField(max_length=200)),
                ('razonDeEntrega', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.sucursal')),
            ],
        ),
    ]
