# Generated by Django 4.2.1 on 2025-03-28 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_asesor_alter_resgistrosasociado_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resgistrosasociado',
            name='asesor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resgistrosasociado',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Asesor',
        ),
    ]
