# Generated by Django 4.2.20 on 2025-04-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_resgistrosasociado_asesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='correo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
