# Generated by Django 4.2.7 on 2025-05-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_asociado_acumaportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='rentabilidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
