# Generated by Django 4.2.7 on 2025-06-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_asociado_rentabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='calificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asociado',
            name='salario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
