# Generated by Django 4.2.1 on 2025-06-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_asociado_calificacion_asociado_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='diasVencidos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
