# Generated by Django 4.2.1 on 2025-06-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_asociado_diasvencidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='rentabilidadPor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
